// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package dynamic_mailer is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	Payload
	Response
*/
package dynamic_mailer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Payload struct {
	ReferenceUuid string `protobuf:"bytes,1,opt,name=reference_uuid,json=referenceUuid" json:"reference_uuid,omitempty"`
	Event         string `protobuf:"bytes,2,opt,name=event" json:"event,omitempty"`
	Email         string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Payload) GetReferenceUuid() string {
	if m != nil {
		return m.ReferenceUuid
	}
	return ""
}

func (m *Payload) GetEvent() string {
	if m != nil {
		return m.Event
	}
	return ""
}

func (m *Payload) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Response struct {
	Status int32 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Response) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Payload)(nil), "dynamic_mailer.Payload")
	proto.RegisterType((*Response)(nil), "dynamic_mailer.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Messages service

type MessagesClient interface {
	SendIt(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Response, error)
}

type messagesClient struct {
	cc *grpc.ClientConn
}

func NewMessagesClient(cc *grpc.ClientConn) MessagesClient {
	return &messagesClient{cc}
}

func (c *messagesClient) SendIt(ctx context.Context, in *Payload, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := grpc.Invoke(ctx, "/dynamic_mailer.Messages/SendIt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Messages service

type MessagesServer interface {
	SendIt(context.Context, *Payload) (*Response, error)
}

func RegisterMessagesServer(s *grpc.Server, srv MessagesServer) {
	s.RegisterService(&_Messages_serviceDesc, srv)
}

func _Messages_SendIt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Payload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessagesServer).SendIt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dynamic_mailer.Messages/SendIt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessagesServer).SendIt(ctx, req.(*Payload))
	}
	return interceptor(ctx, in, info, handler)
}

var _Messages_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dynamic_mailer.Messages",
	HandlerType: (*MessagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendIt",
			Handler:    _Messages_SendIt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0xa9, 0xcc, 0x4b, 0xcc,
	0xcd, 0x4c, 0x8e, 0xcf, 0x4d, 0xcc, 0xcc, 0x49, 0x2d, 0x52, 0x8a, 0xe1, 0x62, 0x0f, 0x48, 0xac,
	0xcc, 0xc9, 0x4f, 0x4c, 0x11, 0x52, 0xe5, 0xe2, 0x2b, 0x4a, 0x4d, 0x4b, 0x2d, 0x4a, 0xcd, 0x4b,
	0x4e, 0x8d, 0x2f, 0x2d, 0xcd, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x85, 0x8b,
	0x86, 0x96, 0x66, 0xa6, 0x08, 0x89, 0x70, 0xb1, 0xa6, 0x96, 0xa5, 0xe6, 0x95, 0x48, 0x30, 0x81,
	0x65, 0x21, 0x1c, 0xb0, 0x28, 0xc8, 0x48, 0x09, 0x66, 0xa8, 0x28, 0x88, 0xa3, 0xa4, 0xc4, 0xc5,
	0x11, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc6, 0xc5, 0x56, 0x5c, 0x92, 0x58,
	0x52, 0x5a, 0x0c, 0x36, 0x96, 0x35, 0x08, 0xca, 0x33, 0xf2, 0xe4, 0xe2, 0xf0, 0x85, 0x38, 0xb1,
	0x58, 0xc8, 0x96, 0x8b, 0x2d, 0x38, 0x35, 0x2f, 0xc5, 0xb3, 0x44, 0x48, 0x5c, 0x0f, 0xd5, 0xa1,
	0x7a, 0x50, 0x57, 0x4a, 0x49, 0xa0, 0x4b, 0xc0, 0x2c, 0x50, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd1,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xd2, 0xc5, 0x10, 0x67, 0xf4, 0x00, 0x00, 0x00,
}
